version: '3'

services:
  server:
    container_name: 'kubevious-portable-server'
    build: ./src
    expose:
      - 5001
    ports:
      - 5001:5001
    volumes:
      - ./src:/usr/src/app

  client:
    container_name: 'kubevious-portable-ui'
    build: ./client
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./client:/usr/src/client
    links:
      - server
    tty: true
    command: npm start





